### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by fabrizziocht** [BracketCove/AndroidRestTutorial#4]
Hello, I'm trying to run the code but I got this error:

`E/ListActivity: setUpAdapterAndView: Only the original thread that created a view hierarchy can touch its views.
W/System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
W/System.err:     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7286)
                  at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1155)
                  at android.view.View.requestLayout(View.java:21926)
I/chatty: uid=10096(u0_a96) RxCachedThreadS identical 4 lines
W/System.err:     at android.view.View.requestLayout(View.java:21926)
                  at android.support.constraint.ConstraintLayout.requestLayout(ConstraintLayout.java:1959)
W/System.err:     at android.view.View.requestLayout(View.java:21926)
                  at android.view.View.setFlags(View.java:13289)
                  at android.view.View.setVisibility(View.java:9382)
                  at android.support.v4.widget.ContentLoadingProgressBar.hide(ContentLoadingProgressBar.java:102)
                  at com.wiseassblog.startingpoint.repolist.ListActivity.setUpAdapterAndView(ListActivity.java:112)
                  at com.wiseassblog.startingpoint.repolist.ListPresenter$1.onNext(ListPresenter.java:83)
W/System.err:     at com.wiseassblog.startingpoint.repolist.ListPresenter$1.onNext(ListPresenter.java:72)`

This problem happens when I set de scheduler like this:

`    disposable.add(
                datasource.getUserRepositories(user).observeOn(scheduler.getUiScheduler()) ...... `

but when I'm changing to use the MainThread, there is no problem:
`    disposable.add(
                datasource.getUserRepositories(user).observeOn(AndroidSchedulers.mainThread()) ...... `
so how can I solve really this? What am I doing wrong? I'm trying to run the app project but I'm getting the same problem.
Thanks for your response.

**Comment by BracketCove** [comment]
I believe the issue is that you may be deploying to the wrong build variant. Be sure to set it for 'prodDebug' if testing the App on a device/emulator. If executing Unit Tests, it must be set to 'mockDebug'. This would explain why AndroidSchedulers.mainThread works.

Hopefully that fixes the issue for you.
